spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    baseline-on-migrate: true

server:
  port: 8081
