CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    display_name VARCHAR(255),
    role VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6)
);

CREATE TABLE school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    rank VARCHAR(255),
    s_points INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP(6)
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    full_name VARCHAR(255),
    passport_data VARCHAR(128),
    entrance_exam_score INTEGER,
    contact_info VARCHAR(255),
    birth_date DATE,
    class_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_users_account FOREIGN KEY (account_id) REFERENCES app_users (id),
    CONSTRAINT fk_users_class FOREIGN KEY (class_id) REFERENCES school_classes (id)
);

CREATE TABLE exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    subject VARCHAR(255),
    status VARCHAR(255),
    class_id BIGINT,
    created_by_id BIGINT,
    duration_minutes INTEGER,
    total_questions INTEGER,
    description VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_start_time TIMESTAMP(6),
    start_time TIMESTAMP(6),
    end_time TIMESTAMP(6),
    CONSTRAINT fk_exam_sessions_class FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_exam_sessions_created_by FOREIGN KEY (created_by_id) REFERENCES app_users (id)
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    order_index INTEGER,
    text VARCHAR(255),
    type VARCHAR(255),
    options_json VARCHAR(4000),
    correct_answer VARCHAR(4000),
    max_score INTEGER,
    metadata_json VARCHAR(4000)
);

CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    user_id BIGINT,
    question_id BIGINT,
    text VARCHAR(2000),
    saved_at TIMESTAMP(6),
    score INTEGER,
    final_submitted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    started_at TIMESTAMP(6),
    submitted_at TIMESTAMP(6),
    CONSTRAINT uk_exam_attempt_student UNIQUE (session_id, student_id),
    CONSTRAINT fk_exam_attempt_session FOREIGN KEY (session_id) REFERENCES exam_sessions (id),
    CONSTRAINT fk_exam_attempt_student FOREIGN KEY (student_id) REFERENCES user_profiles (id)
);

CREATE TABLE exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    raw_score INTEGER NOT NULL DEFAULT 0,
    violation_penalty INTEGER NOT NULL DEFAULT 0,
    final_score INTEGER NOT NULL DEFAULT 0,
    rank_place INTEGER,
    graded_at TIMESTAMP(6),
    CONSTRAINT uk_exam_result_student UNIQUE (session_id, user_id),
    CONSTRAINT fk_exam_result_session FOREIGN KEY (session_id) REFERENCES exam_sessions (id),
    CONSTRAINT fk_exam_result_user FOREIGN KEY (user_id) REFERENCES user_profiles (id)
);

CREATE TABLE violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    user_id BIGINT,
    type VARCHAR(255),
    description VARCHAR(255),
    evidence_path VARCHAR(255),
    points_penalty INTEGER,
    affects_expulsion BOOLEAN NOT NULL DEFAULT FALSE,
    time TIMESTAMP(6)
);

CREATE TABLE secret_votings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    class_id BIGINT NOT NULL,
    created_by_id BIGINT,
    status VARCHAR(255),
    started_at TIMESTAMP(6),
    ends_at TIMESTAMP(6),
    finished_at TIMESTAMP(6),
    CONSTRAINT fk_secret_votings_class FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_secret_votings_created_by FOREIGN KEY (created_by_id) REFERENCES app_users (id)
);

CREATE TABLE voting_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    candidate_user_id BIGINT,
    CONSTRAINT fk_voting_options_voting FOREIGN KEY (voting_id) REFERENCES secret_votings (id)
);

CREATE TABLE voting_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    voted_at TIMESTAMP(6),
    CONSTRAINT uk_voting_receipt_student UNIQUE (voting_id, student_id),
    CONSTRAINT fk_voting_receipt_voting FOREIGN KEY (voting_id) REFERENCES secret_votings (id),
    CONSTRAINT fk_voting_receipt_student FOREIGN KEY (student_id) REFERENCES user_profiles (id)
);

CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_id BIGINT NOT NULL,
    encrypted_value VARCHAR(255) NOT NULL,
    anonymous_voter_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_vote_anonymous_voter UNIQUE (voting_id, anonymous_voter_hash)
);

CREATE TABLE privilege_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    requested_by_id BIGINT,
    privilege_title VARCHAR(255),
    student_wishes VARCHAR(2000),
    required_s_points INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    CONSTRAINT fk_privilege_requests_class FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_privilege_requests_requested_by FOREIGN KEY (requested_by_id) REFERENCES app_users (id)
);

CREATE INDEX idx_questions_session_id ON questions (session_id);
CREATE INDEX idx_answers_session_user ON answers (session_id, user_id);
CREATE INDEX idx_violations_session_user ON violations (session_id, user_id);
CREATE INDEX idx_votes_voting_id ON votes (voting_id);
