ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS s_points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE exam_results
    ADD COLUMN IF NOT EXISTS awarded_s_points INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS s_point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    session_id BIGINT,
    points_delta INTEGER NOT NULL,
    resulting_balance INTEGER NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_s_point_transaction_user FOREIGN KEY (user_id) REFERENCES user_profiles (id),
    CONSTRAINT fk_s_point_transaction_class FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT fk_s_point_transaction_session FOREIGN KEY (session_id) REFERENCES exam_sessions (id)
);

CREATE INDEX IF NOT EXISTS idx_s_point_transactions_user_created
    ON s_point_transactions (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_s_point_transactions_class_created
    ON s_point_transactions (class_id, created_at);
